trainer:
  max_epochs: 1
  # avoid step-based stopping for this quick check
  max_steps: -1

  # keep it simple locally
  precision: "16-mixed"
  accumulate_grad_batches: 1
  devices: 1

  # optional: speed up validation for smoke test
  limit_val_batches: 2
  limit_train_batches: 50 # optional: makes the run finish fast
  val_check_interval: 1.0

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      resume: allow
      project: "eomt"
      name: "local_smoke_stageA_head_1epoch"

model:
  init_args:
    finetune_stage: "A_head"
    lr: 0.001
    weight_decay: 0.01
    use_logit_norm: True

    # if you load a checkpoint to fine-tune:
    # ckpt_path: /path/to/pytorch_model.bin
    # load_ckpt_class_head: True
